import type { Plan } from "./types";

/**
 * Plan library. Loads, sets and grades are left to the athlete; prescriptions
 * give rep ranges, rest and intent only.
 */
export const PLANS: Plan[] = [
  /* ============================ FREE WEIGHTS ============================ */
  {
    id: "fw-push",
    name: "Push Day",
    category: "freeweights",
    minutes: [60, 75],
    tagline: "Horizontal and vertical pressing, plus the shoulder and wrist work climbers skip.",
    equipment: ["Barbell + rack", "Dumbbells", "Bench"],
    focus: ["Chest", "Shoulders", "Triceps", "Antagonist balance"],
    stress: ["push"],
    notes: [
      "Pressing volume is antagonist work for a climber. It keeps the shoulder joint balanced against all that pulling.",
      "Block A is the only true strength block. Everything after it runs as a superset to keep the session under 75 minutes.",
    ],
    blocks: [
      {
        id: "fwp-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        note: "Straight through, no rest needed.",
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "shoulder-pass-through", pres: "12 reps" },
          { ex: "pushup", pres: "10 reps", note: "Bodyweight only, primer set." },
        ],
      },
      {
        id: "fwp-a",
        tag: "A",
        title: "Primary Press",
        kind: "straight",
        rounds: 4,
        rest: "2-3 min",
        minutes: 16,
        note: "Heaviest work of the day. Take the full rest, these sets are not supersetted.",
        slots: [{ ex: "bench-press", pres: "4 x 5-6", note: "Swap in dumbbell bench if you have no spotter." }],
      },
      {
        id: "fwp-b",
        tag: "B",
        title: "Superset: Overhead + Rear Delt",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        note: "Press then immediately fly. The rear delt work is light, so it doubles as recovery.",
        slots: [
          { ex: "ohp", pres: "6-8 reps" },
          { ex: "rear-delt-fly", pres: "12-15 reps" },
        ],
      },
      {
        id: "fwp-c",
        tag: "C",
        title: "Superset: Incline + Lateral",
        kind: "superset",
        rounds: 3,
        rest: "75-90s between rounds",
        minutes: 11,
        slots: [
          { ex: "incline-db-press", pres: "8-10 reps" },
          { ex: "lateral-raise", pres: "12-15 reps" },
        ],
      },
      {
        id: "fwp-d",
        tag: "D",
        title: "Superset: Triceps + Core",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 10,
        slots: [
          { ex: "skull-crusher", pres: "10-12 reps" },
          { ex: "dead-bug", pres: "8-10 per side" },
        ],
      },
      {
        id: "fwp-e",
        tag: "E",
        title: "Finisher: Elbow & Wrist Insurance",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        note: "Non-negotiable if you climb hard. Light loads, high reps.",
        slots: [
          { ex: "wrist-extension", pres: "15-20 reps" },
          { ex: "reverse-curl", pres: "15 reps" },
          { ex: "shoulder-er", pres: "12-15 per side" },
        ],
      },
    ],
  },

  {
    id: "fw-pull",
    name: "Pull Day",
    category: "freeweights",
    minutes: [60, 75],
    tagline: "Heavy pulling strength with grip and elbow work built in.",
    equipment: ["Pull-up bar", "Barbell", "Dumbbells", "Bench"],
    focus: ["Lats", "Mid back", "Biceps", "Grip"],
    stress: ["pull"],
    notes: [
      "Do not run this within 48 hours of a hard hangboard or limit bouldering session. The fingers and elbows need the gap.",
      "If your bar work is fresh from climbing, drop block A to 3 sets and add a set to block C instead.",
    ],
    blocks: [
      {
        id: "fwl-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "prone-ytw", pres: "6 each position", note: "Bodyweight, activation only." },
        ],
      },
      {
        id: "fwl-a",
        tag: "A",
        title: "Primary Pull",
        kind: "straight",
        rounds: 5,
        rest: "2-3 min",
        minutes: 18,
        note: "Full range, dead hang to chin over bar. Add weight only when 5 clean reps are easy.",
        slots: [{ ex: "weighted-pullup", pres: "5 x 4-6", note: "Bodyweight pull-ups or barbell rows if you have no belt." }],
      },
      {
        id: "fwl-b",
        tag: "B",
        title: "Superset: Row + Scapular",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        slots: [
          { ex: "barbell-row", pres: "6-8 reps" },
          { ex: "prone-ytw", pres: "8 each position", note: "Light dumbbells, 2.5-5 lb is plenty." },
        ],
      },
      {
        id: "fwl-c",
        tag: "C",
        title: "Superset: Unilateral Row + Neutral Curl",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "db-row", pres: "8-10 per side" },
          { ex: "hammer-curl", pres: "10-12 reps" },
        ],
      },
      {
        id: "fwl-d",
        tag: "D",
        title: "Superset: Lat Stretch-Load + Elbow",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 9,
        slots: [
          { ex: "db-pullover", pres: "12 reps" },
          { ex: "reverse-curl", pres: "12-15 reps", note: "Deliberately light. The elbow is the point, not the forearm size." },
        ],
      },
      {
        id: "fwl-e",
        tag: "E",
        title: "Finisher: Grip & Trunk",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "dead-hang", pres: "25-30s" },
          { ex: "wrist-extension", pres: "15-20 reps" },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
    ],
  },

  {
    id: "fw-legs",
    name: "Legs & Core",
    category: "freeweights",
    minutes: [55, 70],
    tagline: "Squat, hinge, and the single-leg strength that high steps actually require.",
    equipment: ["Barbell + rack", "Dumbbells", "Bench or chair", "Step"],
    focus: ["Quads", "Glutes", "Hamstrings", "Trunk"],
    stress: ["legs"],
    notes: [
      "Climbers under-train legs and then wonder why rock-overs feel like a bench press. Single-leg work in block C is the highest-transfer item here.",
      "Schedule this the day before a rest day or a technique day, not before limit bouldering.",
    ],
    blocks: [
      {
        id: "fwg-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 9,
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
          { ex: "deep-squat-hold", pres: "45s" },
          { ex: "glute-bridge", pres: "10 per side" },
        ],
      },
      {
        id: "fwg-a",
        tag: "A",
        title: "Squat",
        kind: "straight",
        rounds: 4,
        rest: "2-3 min",
        minutes: 16,
        slots: [{ ex: "back-squat", pres: "4 x 5", note: "Goblet squat is a fine substitute; just go higher on reps, 4 x 10." }],
      },
      {
        id: "fwg-b",
        tag: "B",
        title: "Superset: Hinge + Calf",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        slots: [
          { ex: "rdl", pres: "8 reps" },
          { ex: "calf-raise", pres: "15-20 per side" },
        ],
      },
      {
        id: "fwg-c",
        tag: "C",
        title: "Superset: Single-Leg + Glute",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 13,
        note: "The most climbing-specific block in this plan. Do not rush the split squats.",
        slots: [
          { ex: "bulgarian-split-squat", pres: "8-10 per side" },
          { ex: "hip-thrust", pres: "12-15 reps" },
        ],
      },
      {
        id: "fwg-d",
        tag: "D",
        title: "Superset: High Step + Adductor",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 10,
        slots: [
          { ex: "high-step-up", pres: "10 per side" },
          { ex: "copenhagen", pres: "20-30s per side" },
        ],
      },
      {
        id: "fwg-e",
        tag: "E",
        title: "Finisher: Trunk",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "suitcase-carry", pres: "35s per side" },
          { ex: "hollow-hold", pres: "30s" },
          { ex: "bird-dog", pres: "8 per side" },
        ],
      },
    ],
  },

  {
    id: "fw-express",
    name: "Dumbbell Express",
    category: "freeweights",
    minutes: [40, 55],
    tagline: "One pair of dumbbells, all supersets, in and out in under an hour.",
    equipment: ["Dumbbells", "Chair or bench"],
    focus: ["Full body", "Time-efficient", "Minimal equipment"],
    stress: ["push", "pull", "legs"],
    notes: [
      "Everything here is paired. The only rest is between rounds, which is what keeps it under an hour.",
      "This is the fallback session for a week where climbing took priority. Two per week maintains strength without interfering.",
    ],
    blocks: [
      {
        id: "fwe-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "pulse-raiser", pres: "3 min" },
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "squat-to-stand", pres: "8 reps" },
          { ex: "scap-pushup", pres: "10 reps" },
        ],
      },
      {
        id: "fwe-a",
        tag: "A",
        title: "Superset: Squat + Row",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 14,
        slots: [
          { ex: "goblet-squat", pres: "10 reps" },
          { ex: "db-row", pres: "10 per side" },
        ],
      },
      {
        id: "fwe-b",
        tag: "B",
        title: "Superset: Press + Hinge",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 13,
        slots: [
          { ex: "db-floor-press", pres: "10 reps" },
          { ex: "rdl", pres: "10 reps", note: "Dumbbells, controlled. Feel the hamstrings, not the low back." },
        ],
      },
      {
        id: "fwe-c",
        tag: "C",
        title: "Superset: Overhead + Rear Delt",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "db-push-press", pres: "8 reps" },
          { ex: "rear-delt-fly", pres: "15 reps" },
        ],
      },
      {
        id: "fwe-d",
        tag: "D",
        title: "Circuit: Arms, Forearms, Core",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 9,
        note: "Minimal rest inside the round. Move.",
        slots: [
          { ex: "hammer-curl", pres: "12 reps" },
          { ex: "oh-tricep-ext", pres: "12 reps" },
          { ex: "wrist-extension", pres: "15 reps" },
          { ex: "plank", pres: "45s" },
        ],
      },
    ],
  },

  /* ============================= BODYWEIGHT ============================= */
  {
    id: "bw-push",
    name: "Bodyweight Push & Core",
    category: "bodyweight",
    minutes: [45, 55],
    tagline: "Floor and one chair. Pressing volume and trunk tension, no equipment.",
    equipment: ["Floor", "One sturdy chair"],
    focus: ["Chest", "Shoulders", "Triceps", "Core"],
    stress: ["push"],
    notes: [
      "With no external load, difficulty comes from leverage and tempo. Elevating the feet or slowing the lowering is how you progress, not adding reps forever.",
      "Check the chair is stable before block A. A dining chair works; an office chair does not.",
    ],
    blocks: [
      {
        id: "bwp-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 8,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "worlds-greatest-stretch", pres: "4 per side" },
          { ex: "pushup", pres: "8 reps", note: "Knees down if needed. Primer only." },
        ],
      },
      {
        id: "bwp-a",
        tag: "A",
        title: "Superset: Decline Push + Dip",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 14,
        note: "Feet on the chair for the push-up, hands on the chair for the dip. No repositioning time.",
        slots: [
          { ex: "decline-pushup", pres: "8-12 reps" },
          { ex: "chair-dip", pres: "10-15 reps" },
        ],
      },
      {
        id: "bwp-b",
        tag: "B",
        title: "Superset: Vertical Press + Hollow",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "pike-pushup", pres: "6-10 reps", note: "Feet on the chair to make it a near-handstand press." },
          { ex: "hollow-hold", pres: "25-40s" },
        ],
      },
      {
        id: "bwp-c",
        tag: "C",
        title: "Superset: Tempo / Unilateral + Side Plank",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "tempo-pushup", pres: "6 reps @ 3s down", note: "Swap for archer push-ups once tempo reps are easy." },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
      {
        id: "bwp-d",
        tag: "D",
        title: "Circuit: Shoulder Control & Core",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 10,
        slots: [
          { ex: "shoulder-taps", pres: "20 taps" },
          { ex: "ab-rollout", pres: "8-10 reps", note: "Socks on a hard floor, or a towel." },
          { ex: "reverse-snow-angel", pres: "15 reps" },
        ],
      },
      {
        id: "bwp-e",
        tag: "E",
        title: "Finisher",
        kind: "straight",
        rounds: 3,
        rest: "45s",
        minutes: 4,
        slots: [{ ex: "wall-handstand", pres: "3 x 20-40s", note: "Or a feet-on-chair pike hold if the wall is not an option." }],
      },
    ],
  },

  {
    id: "bw-pull",
    name: "Bodyweight Pull & Posterior",
    category: "bodyweight",
    minutes: [40, 50],
    tagline: "The honest version of bodyweight pulling: scapular control, posterior chain, isometrics.",
    equipment: ["Floor", "One sturdy chair", "Towel", "Socks or sliders"],
    focus: ["Upper back", "Posterior chain", "Shoulder health"],
    stress: ["pull"],
    notes: [
      "Straight talk: without a bar, rings or a door pull-up bar you cannot meaningfully load a vertical pull. This session trains scapular control, the posterior chain and isometric pulling instead.",
      "If bodyweight days are a regular part of your week, a $25 doorway pull-up bar changes what is possible here more than any other purchase.",
      "For a climber this session is still worth running: the lower trap and rear delt work is exactly what heavy pulling neglects.",
    ],
    blocks: [
      {
        id: "bwl-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 8,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "thoracic-rotation", pres: "6 per side" },
          { ex: "prone-ytw", pres: "5 each position" },
          { ex: "finger-rolls", pres: "20 reps" },
        ],
      },
      {
        id: "bwl-a",
        tag: "A",
        title: "Superset: Scapular Endurance",
        kind: "superset",
        rounds: 4,
        rest: "60s between rounds",
        minutes: 12,
        note: "Both of these look trivial and are not. Go slow enough that round 4 is hard.",
        slots: [
          { ex: "prone-ytw", pres: "8 each position" },
          { ex: "reverse-snow-angel", pres: "15 reps" },
        ],
      },
      {
        id: "bwl-b",
        tag: "B",
        title: "Superset: Lat Pull + Isometric Row",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "floor-lat-pull", pres: "8-12 reps" },
          { ex: "towel-row-iso", pres: "6 x 10s pulls", note: "Towel around a door handle, lean back and pull hard." },
        ],
      },
      {
        id: "bwl-c",
        tag: "C",
        title: "Superset: Hinge + Glute",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "rdl", pres: "12 per side", note: "Single-leg, bodyweight. Slow, reach the floor with the fingertips." },
          { ex: "glute-bridge", pres: "12 per side" },
        ],
      },
      {
        id: "bwl-d",
        tag: "D",
        title: "Circuit: Extension & Stability",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 9,
        slots: [
          { ex: "superman", pres: "30s hold" },
          { ex: "bird-dog", pres: "8 per side" },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
    ],
  },

  {
    id: "bw-legs",
    name: "Bodyweight Legs",
    category: "bodyweight",
    minutes: [40, 50],
    tagline: "Single-leg strength, knee control and hip range. Chair does most of the work.",
    equipment: ["Floor", "One sturdy chair", "Step (optional)"],
    focus: ["Quads", "Glutes", "Single-leg", "Hip mobility"],
    stress: ["legs"],
    notes: [
      "Bodyweight legs get hard through unilateral loading and tempo, not volume. If a set of 20 feels easy, move to the harder progression instead of doing 30.",
    ],
    blocks: [
      {
        id: "bwg-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 8,
        slots: [
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "squat-to-stand", pres: "8 reps" },
          { ex: "deep-squat-hold", pres: "40s" },
          { ex: "glute-bridge", pres: "10 per side" },
        ],
      },
      {
        id: "bwg-a",
        tag: "A",
        title: "Superset: Tempo Squat + Assisted Pistol",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 14,
        slots: [
          { ex: "goblet-squat", pres: "15 reps @ 3s down", note: "No weight: bodyweight squat, arms forward, 3 second lowering." },
          { ex: "pistol-progression", pres: "8 per side" },
        ],
      },
      {
        id: "bwg-b",
        tag: "B",
        title: "Superset: Split Squat + Single-Leg Glute",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        slots: [
          { ex: "bulgarian-split-squat", pres: "10 per side", note: "Rear foot on the chair, bodyweight only." },
          { ex: "glute-bridge", pres: "12 per side", note: "Heel on the chair to increase range." },
        ],
      },
      {
        id: "bwg-c",
        tag: "C",
        title: "Superset: Lunge + Calf",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 10,
        slots: [
          { ex: "reverse-lunge", pres: "12 per side" },
          { ex: "calf-raise", pres: "15-20 per side" },
        ],
      },
      {
        id: "bwg-d",
        tag: "D",
        title: "Circuit: Endurance & Hips",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "wall-sit", pres: "45-60s" },
          { ex: "copenhagen", pres: "20-30s per side" },
          { ex: "step-down", pres: "8 per side" },
          { ex: "high-step-drill", pres: "8 per side" },
        ],
      },
    ],
  },

  {
    id: "bw-express",
    name: "Bodyweight Express Circuit",
    category: "bodyweight",
    minutes: [25, 35],
    tagline: "Hotel-room session. Six movements, 40 seconds on, 20 off, four rounds.",
    equipment: ["Floor", "One chair"],
    focus: ["Full body", "Travel", "Minimal time"],
    stress: ["push", "legs"],
    notes: [
      "Timed intervals, not rep targets. Use the interval timer in the session: 40s work, 20s rest.",
      "Four rounds is roughly 24 minutes of work. Three rounds is a legitimate short day.",
    ],
    blocks: [
      {
        id: "bwx-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "squat-to-stand", pres: "8 reps" },
          { ex: "scap-pushup", pres: "10 reps" },
        ],
      },
      {
        id: "bwx-a",
        tag: "A",
        title: "Circuit: 40s On / 20s Off",
        kind: "interval",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 26,
        note: "Run the interval timer. One pass through all six is a round.",
        interval: { work: 40, rest: 20, reps: 6, setRest: 90, sets: 4 },
        slots: [
          { ex: "goblet-squat", pres: "40s", note: "Bodyweight, continuous." },
          { ex: "decline-pushup", pres: "40s" },
          { ex: "reverse-lunge", pres: "40s alternating" },
          { ex: "chair-dip", pres: "40s" },
          { ex: "reverse-snow-angel", pres: "40s" },
          { ex: "hollow-hold", pres: "40s" },
        ],
      },
      {
        id: "bwx-b",
        tag: "B",
        title: "Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        slots: [
          { ex: "hamstring-stretch", pres: "45s per side" },
          { ex: "pigeon-stretch", pres: "60s per side" },
        ],
      },
    ],
  },

  /* =========================== CLIMBING GYM =========================== */
  {
    id: "cg-max",
    name: "Hangboard & Limit Boulders",
    category: "gym",
    minutes: [100, 120],
    tagline: "Max hangs, then limit bouldering, then antagonist work. The hardest day of the week.",
    equipment: ["Climbing wall", "Hangboard", "Free weights"],
    focus: ["Finger strength", "Max power", "Recruitment"],
    stress: ["fingers", "pull"],
    notes: [
      "Prerequisite: roughly a year of consistent climbing before loading a hangboard. Tendons adapt far slower than muscle.",
      "Never start hangboarding cold, and never on consecutive days. Two finger-intensive sessions per week is the ceiling for most people.",
      "Any sharp, hot or localized pain in a single finger ends the finger work for the day. No exceptions.",
      "Order matters: fingers and power come first, while the nervous system is fresh. Strength work last.",
    ],
    blocks: [
      {
        id: "cgm-w",
        tag: "W",
        title: "Warm-Up (do not skip)",
        kind: "circuit",
        rounds: 1,
        minutes: 18,
        note: "18 minutes. This is the price of admission for max hangs.",
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "easy-climbing", pres: "4-5 problems" },
          { ex: "progressive-hangs", pres: "3 x 10-15s" },
          { ex: "moderate-climbing", pres: "2 problems" },
        ],
      },
      {
        id: "cgm-a",
        tag: "A",
        title: "Hangboard: Max Hangs",
        kind: "interval",
        rounds: 5,
        rest: "2-3 min between sets",
        minutes: 20,
        note: "Half crimp, 20mm edge. Effort where you could hold 2-3 seconds longer, never to failure.",
        interval: { work: 10, rest: 0, reps: 1, setRest: 150, sets: 5 },
        slots: [{ ex: "max-hang", pres: "5 x 7-10s", note: "Add or remove weight to keep every set at the same effort." }],
      },
      {
        id: "cgm-b",
        tag: "B",
        title: "Limit Bouldering",
        kind: "straight",
        rounds: 8,
        rest: "3-5 min between attempts",
        minutes: 35,
        note: "2-3 problems at or just past your limit. When attempts visibly degrade, the block is over even if time remains.",
        unit: "Attempts",
        slots: [{ ex: "limit-boulder", pres: "8-10 attempts" }],
      },
      {
        id: "cgm-c",
        tag: "C",
        title: "Superset: Weighted Pull + Overhead",
        kind: "superset",
        rounds: 3,
        rest: "2 min between rounds",
        minutes: 12,
        slots: [
          { ex: "weighted-pullup", pres: "4-5 reps" },
          { ex: "ohp", pres: "8 reps", note: "Dumbbells. Antagonist work, moderate load." },
        ],
      },
      {
        id: "cgm-d",
        tag: "D",
        title: "Superset: Tension Core + Press",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "front-lever-tuck", pres: "6-8s hold" },
          { ex: "pushup", pres: "12-15 reps" },
        ],
      },
      {
        id: "cgm-e",
        tag: "E",
        title: "Finisher: Elbow & Cool-Down",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 10,
        slots: [
          { ex: "wrist-extension", pres: "15-20 reps" },
          { ex: "band-finger-ext", pres: "20 reps" },
          { ex: "shoulder-er", pres: "12 per side" },
          { ex: "forearm-flush", pres: "60s" },
        ],
      },
    ],
  },

  {
    id: "cg-power-endurance",
    name: "Power Endurance 4x4s",
    category: "gym",
    minutes: [85, 100],
    tagline: "Four flash-grade boulders back to back, four times. Then pulling and core.",
    equipment: ["Climbing wall", "Pull-up bar", "Free weights"],
    focus: ["Power endurance", "Lactate tolerance", "Mental grit"],
    stress: ["fingers", "pull"],
    notes: [
      "This session is supposed to feel awful by set 3. That is the training effect, not a sign you picked the wrong problems.",
      "Run it at most once a week, and not within 48 hours of a max strength day.",
      "Pick the four problems and check they are free before you start. Waiting for a wall between problems kills the stimulus.",
    ],
    blocks: [
      {
        id: "cgp-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 16,
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "easy-climbing", pres: "4 problems" },
          { ex: "moderate-climbing", pres: "2-3 problems" },
          { ex: "campus-recruit", pres: "2 pulls" },
        ],
      },
      {
        id: "cgp-a",
        tag: "A",
        title: "4 x 4s",
        kind: "straight",
        rounds: 4,
        rest: "4-5 min between sets",
        minutes: 35,
        note: "Four problems at your comfortable flash grade, climbed back to back. Only the walk between them is rest. That is one set.",
        unit: "Sets",
        slots: [{ ex: "four-by-four", pres: "4 sets of 4 problems" }],
      },
      {
        id: "cgp-b",
        tag: "B",
        title: "Superset: Pull + Push",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        note: "Fingers are cooked by now, so this is deliberately bar and bodyweight work, not hangboard.",
        slots: [
          { ex: "pullup", pres: "8-10 reps" },
          { ex: "dip-bars", pres: "10-12 reps" },
        ],
      },
      {
        id: "cgp-c",
        tag: "C",
        title: "Circuit: Core",
        kind: "circuit",
        rounds: 3,
        rest: "60s",
        minutes: 10,
        slots: [
          { ex: "hanging-knee-raise", pres: "10 reps" },
          { ex: "plank", pres: "45s" },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
      {
        id: "cgp-d",
        tag: "D",
        title: "Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "cool-down-climb", pres: "5 min" },
          { ex: "forearm-flush", pres: "90s" },
          { ex: "doorway-chest", pres: "45s each" },
        ],
      },
    ],
  },

  {
    id: "cg-repeaters",
    name: "Repeaters & Volume",
    category: "gym",
    minutes: [90, 105],
    tagline: "Hangboard repeaters across two grip types, then high-mileage easy climbing.",
    equipment: ["Climbing wall", "Hangboard", "Free weights"],
    focus: ["Finger strength-endurance", "Grip variety", "Mileage"],
    stress: ["fingers", "pull"],
    notes: [
      "Repeaters are submaximal by design: 7 seconds on, 3 off, six times. Load for RPE 7-8, not failure.",
      "Two grip positions in one session is enough. Half crimp first while you are fresh, then open hand.",
      "If grip position degrades mid-set, stop that set. A sloppy hang trains sloppy fingers.",
    ],
    blocks: [
      {
        id: "cgr-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 16,
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "easy-climbing", pres: "4 problems" },
          { ex: "progressive-hangs", pres: "3 x 10-15s" },
          { ex: "moderate-climbing", pres: "2 problems" },
        ],
      },
      {
        id: "cgr-a",
        tag: "A",
        title: "Repeaters: Half Crimp",
        kind: "interval",
        rounds: 3,
        rest: "3 min between sets",
        minutes: 14,
        note: "7s on / 3s off x 6 reps = one set. Timer is built in.",
        interval: { work: 7, rest: 3, reps: 6, setRest: 180, sets: 3 },
        slots: [{ ex: "repeater-hang", pres: "3 sets x 6 reps", note: "20mm edge, half crimp, thumb off." }],
      },
      {
        id: "cgr-b",
        tag: "B",
        title: "Repeaters: Open Hand / 3-Finger Drag",
        kind: "interval",
        rounds: 3,
        rest: "3 min between sets",
        minutes: 14,
        note: "Same protocol, lighter load. Open hand always feels weaker than half crimp.",
        interval: { work: 7, rest: 3, reps: 6, setRest: 180, sets: 3 },
        slots: [{ ex: "open-hand-hang", pres: "3 sets x 6 reps" }],
      },
      {
        id: "cgr-c",
        tag: "C",
        title: "Volume Climbing",
        kind: "straight",
        rounds: 1,
        minutes: 30,
        note: "Mileage, not difficulty. Rotate wall angles every few problems.",
        slots: [
          { ex: "volume-climbing", pres: "25-30 min" },
          { ex: "downclimbing", pres: "on every easy problem" },
        ],
      },
      {
        id: "cgr-d",
        tag: "D",
        title: "Superset: Row + Press",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 11,
        slots: [
          { ex: "barbell-row", pres: "10 reps" },
          { ex: "ohp", pres: "10 reps" },
        ],
      },
      {
        id: "cgr-e",
        tag: "E",
        title: "Finisher & Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "wrist-extension", pres: "20 reps" },
          { ex: "band-finger-ext", pres: "25 reps" },
          { ex: "forearm-flush", pres: "90s" },
        ],
      },
    ],
  },

  {
    id: "cg-technique",
    name: "Technique & Movement Skills",
    category: "gym",
    minutes: [60, 80],
    tagline: "Drill-based session on easy terrain. Low intensity, high attention. Use it between hard days.",
    equipment: ["Climbing wall", "Hangboard (light)", "Free weights (light)"],
    focus: ["Footwork", "Body positioning", "Efficiency", "Active recovery"],
    notes: [
      "Everything here happens 2-3 grades below your limit. The moment a problem is hard enough to demand effort, the drill stops working.",
      "This is the session that actually raises your ceiling between strength blocks, and the one most people skip because it does not feel like training.",
      "Pick two or three drills per session, not all of them. Depth beats breadth.",
    ],
    blocks: [
      {
        id: "cgt-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 12,
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "finger-rolls", pres: "25 reps" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "high-step-drill", pres: "8 per side" },
          { ex: "easy-climbing", pres: "3-4 problems" },
        ],
      },
      {
        id: "cgt-a",
        tag: "A",
        title: "Footwork Drills",
        kind: "circuit",
        rounds: 1,
        minutes: 18,
        note: "Easy problems only. Zero pump by design.",
        slots: [
          { ex: "silent-feet", pres: "3 problems" },
          { ex: "hover-drill", pres: "2 problems" },
          { ex: "one-touch", pres: "2 problems" },
        ],
      },
      {
        id: "cgt-b",
        tag: "B",
        title: "Body Position Drills",
        kind: "circuit",
        rounds: 1,
        minutes: 18,
        slots: [
          { ex: "straight-arm-drill", pres: "3 x 2 min traverse" },
          { ex: "flag-drill", pres: "3 problems" },
          { ex: "downclimbing", pres: "3 problems up and down" },
        ],
      },
      {
        id: "cgt-c",
        tag: "C",
        title: "Light Hangboard (optional)",
        kind: "interval",
        rounds: 3,
        rest: "3 min between sets",
        minutes: 12,
        note: "RPE 6. Skip this entirely if the session is meant as recovery.",
        interval: { work: 7, rest: 3, reps: 6, setRest: 180, sets: 3 },
        slots: [{ ex: "repeater-hang", pres: "3 sets x 6 reps", note: "Noticeably easy. If it feels like work, drop the load." }],
      },
      {
        id: "cgt-d",
        tag: "D",
        title: "Superset: Balance Work",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "pullup", pres: "6 reps" },
          { ex: "pushup", pres: "12 reps" },
          { ex: "dead-bug", pres: "8 per side" },
        ],
      },
      {
        id: "cgt-e",
        tag: "E",
        title: "Mobility Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "pigeon-stretch", pres: "60s per side" },
          { ex: "doorway-chest", pres: "45s each" },
          { ex: "forearm-flush", pres: "60s" },
        ],
      },
    ],
  },

  /* ======================== WARM-UP & RECOVERY ======================== */
  {
    id: "wu-express",
    name: "Express Climbing Warm-Up",
    category: "prep",
    minutes: [12, 15],
    tagline: "Minimum viable warm-up before you pull on anything hard.",
    equipment: ["Climbing wall", "Rubber band (optional)"],
    focus: ["Finger prep", "Movement", "Recruitment"],
    notes: [
      "Twelve minutes. Shorter than this and you are gambling with your fingers and shoulders.",
      "Order is deliberate: general, then local, then specific. Never load fingers before the pulse raiser.",
    ],
    blocks: [
      {
        id: "wux-a",
        tag: "1",
        title: "General",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        slots: [
          { ex: "pulse-raiser", pres: "3-4 min", note: "Enough to break a light sweat." },
          { ex: "finger-rolls", pres: "25 reps" },
        ],
      },
      {
        id: "wux-b",
        tag: "2",
        title: "Mobility",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "deep-squat-hold", pres: "30s" },
        ],
      },
      {
        id: "wux-c",
        tag: "3",
        title: "Finger & Shoulder Prep",
        kind: "circuit",
        rounds: 1,
        minutes: 3,
        slots: [
          { ex: "band-finger-ext", pres: "20 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "progressive-hangs", pres: "2 x 15s" },
        ],
      },
      {
        id: "wux-d",
        tag: "4",
        title: "On the Wall",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "easy-climbing", pres: "3 problems" },
          { ex: "moderate-climbing", pres: "1-2 problems" },
        ],
      },
    ],
  },

  {
    id: "wu-full",
    name: "Full Climbing Warm-Up",
    category: "prep",
    minutes: [25, 30],
    tagline: "For hard sessions, cold gyms, or if you have a history of finger or elbow trouble.",
    equipment: ["Climbing wall", "Hangboard", "Rubber band"],
    focus: ["Thorough finger prep", "Mobility", "Recruitment pyramid"],
    notes: [
      "Use this before any session with max hangs, limit bouldering or a project attempt.",
      "The recruitment step at the end matters: it wakes the nervous system up so your first real attempt is not the warm-up for your second.",
    ],
    blocks: [
      {
        id: "wuf-a",
        tag: "1",
        title: "General",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
        ],
      },
      {
        id: "wuf-b",
        tag: "2",
        title: "Full Mobility",
        kind: "circuit",
        rounds: 1,
        minutes: 7,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "shoulder-pass-through", pres: "12 reps" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "thoracic-rotation", pres: "6 per side" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
          { ex: "high-step-drill", pres: "8 per side" },
          { ex: "deep-squat-hold", pres: "40s" },
        ],
      },
      {
        id: "wuf-c",
        tag: "3",
        title: "Shoulder & Finger Activation",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 6,
        slots: [
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "prone-ytw", pres: "5 each position" },
          { ex: "band-finger-ext", pres: "20 reps" },
        ],
      },
      {
        id: "wuf-d",
        tag: "4",
        title: "Progressive Hangs",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        note: "Feet-assisted to full bodyweight, big holds only.",
        slots: [{ ex: "progressive-hangs", pres: "3-4 x 10-15s" }],
      },
      {
        id: "wuf-e",
        tag: "5",
        title: "Climbing Pyramid",
        kind: "circuit",
        rounds: 1,
        minutes: 9,
        note: "Ramp the grade one step at a time. No jumping straight to your project.",
        slots: [
          { ex: "easy-climbing", pres: "4 problems" },
          { ex: "moderate-climbing", pres: "2-3 problems" },
          { ex: "campus-recruit", pres: "2-3 pulls" },
        ],
      },
    ],
  },

  {
    id: "wu-offwall",
    name: "Pre-Gym Activation (No Wall)",
    category: "prep",
    minutes: [10, 12],
    tagline: "Do this at home or in the parking lot so you arrive already warm.",
    equipment: ["Floor", "Rubber band"],
    focus: ["Desk-body reset", "Hip and shoulder range", "Finger prep"],
    notes: [
      "Built for arriving at the gym after a day at a desk. It does not replace on-the-wall warm-up, it shortens it.",
      "Pair it with the express warm-up at the gym for a complete ramp in about 20 minutes total.",
    ],
    blocks: [
      {
        id: "wuo-a",
        tag: "1",
        title: "Raise & Reset",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 6,
        slots: [
          { ex: "pulse-raiser", pres: "2 min", note: "Stairs, jumping jacks or a brisk walk." },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "thoracic-rotation", pres: "6 per side" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
        ],
      },
      {
        id: "wuo-b",
        tag: "2",
        title: "Activate",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 6,
        slots: [
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "prone-ytw", pres: "5 each position" },
          { ex: "glute-bridge", pres: "10 per side" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "band-finger-ext", pres: "20 reps" },
        ],
      },
    ],
  },

  {
    id: "cool-recovery",
    name: "Post-Session Recovery",
    category: "prep",
    minutes: [15, 20],
    tagline: "Flush the forearms, open what climbing shortened, down-regulate.",
    equipment: ["Floor", "Doorway"],
    focus: ["Forearm recovery", "Hip and chest mobility", "Down-regulation"],
    notes: [
      "Most useful immediately after climbing, while tissue is still warm. Second best is the same evening.",
      "The finger extensor and wrist work here is the same insurance as on strength days. Climbing is all flexion; something has to balance it.",
    ],
    blocks: [
      {
        id: "cr-a",
        tag: "1",
        title: "Flush",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "cool-down-climb", pres: "3-5 min", note: "Skip if you are already off the wall." },
          { ex: "band-finger-ext", pres: "25 reps" },
          { ex: "forearm-flush", pres: "90s" },
        ],
      },
      {
        id: "cr-b",
        tag: "2",
        title: "Open",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "doorway-chest", pres: "45s each position" },
          { ex: "pigeon-stretch", pres: "60-90s per side" },
          { ex: "hamstring-stretch", pres: "60s per side" },
          { ex: "thoracic-rotation", pres: "6 per side" },
        ],
      },
      {
        id: "cr-c",
        tag: "3",
        title: "Down-Regulate",
        kind: "straight",
        rounds: 1,
        minutes: 3,
        slots: [{ ex: "nasal-breathing", pres: "2-3 min" }],
      },
    ],
  },
];

export function planById(id: string): Plan | undefined {
  return PLANS.find((p) => p.id === id);
}

export function totalSlots(plan: Plan): number {
  return plan.blocks.reduce((n, b) => n + b.slots.length * b.rounds, 0);
}
