import type { Plan } from "./types";

/**
 * Plan library. Loads, sets and grades are left to the athlete; prescriptions
 * give rep ranges, rest and intent only.
 */
export const PLANS: Plan[] = [
  /* ============================ FREE WEIGHTS ============================ */
  {
    id: "fw-push",
    name: "Push Day",
    category: "freeweights",
    minutes: [60, 75],
    tagline: "Horizontal and vertical pressing, plus the shoulder and wrist work climbers skip.",
    equipment: ["Barbell + rack", "Dumbbells", "Bench"],
    focus: ["Chest", "Shoulders", "Triceps", "Antagonist balance"],
    stress: ["push"],
    notes: [
      "Pressing volume is antagonist work for a climber. It keeps the shoulder joint balanced against all that pulling.",
      "Block A is the only true strength block. Everything after it runs as a superset to keep the session under 75 minutes.",
    ],
    blocks: [
      {
        id: "fwp-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        note: "Straight through, no rest needed.",
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "shoulder-pass-through", pres: "12 reps" },
          { ex: "pushup", pres: "10 reps", note: "Bodyweight only, primer set." },
        ],
      },
      {
        id: "fwp-a",
        tag: "A",
        title: "Primary Press",
        kind: "straight",
        rounds: 4,
        rest: "2-3 min",
        minutes: 16,
        note: "Heaviest work of the day. Take the full rest, these sets are not supersetted.",
        slots: [{ ex: "bench-press", pres: "4 x 5-6", note: "Swap in dumbbell bench if you have no spotter." }],
      },
      {
        id: "fwp-b",
        tag: "B",
        title: "Superset: Overhead + Rear Delt",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        note: "Press then immediately fly. The rear delt work is light, so it doubles as recovery.",
        slots: [
          { ex: "ohp", pres: "6-8 reps" },
          { ex: "rear-delt-fly", pres: "12-15 reps" },
        ],
      },
      {
        id: "fwp-c",
        tag: "C",
        title: "Superset: Incline + Lateral",
        kind: "superset",
        rounds: 3,
        rest: "75-90s between rounds",
        minutes: 11,
        slots: [
          { ex: "incline-db-press", pres: "8-10 reps" },
          { ex: "lateral-raise", pres: "12-15 reps" },
        ],
      },
      {
        id: "fwp-d",
        tag: "D",
        title: "Superset: Triceps + Core",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 10,
        slots: [
          { ex: "skull-crusher", pres: "10-12 reps" },
          { ex: "dead-bug", pres: "8-10 per side" },
        ],
      },
      {
        id: "fwp-e",
        tag: "E",
        title: "Finisher: Elbow & Wrist Insurance",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        note: "Non-negotiable if you climb hard. Light loads, high reps.",
        slots: [
          { ex: "wrist-extension", pres: "15-20 reps" },
          { ex: "reverse-curl", pres: "15 reps" },
          { ex: "shoulder-er", pres: "12-15 per side" },
        ],
      },
    ],
  },

  {
    id: "fw-pull",
    name: "Pull Day",
    category: "freeweights",
    minutes: [60, 75],
    tagline: "Heavy pulling strength with grip and elbow work built in.",
    equipment: ["Pull-up bar", "Barbell", "Dumbbells", "Bench"],
    focus: ["Lats", "Mid back", "Biceps", "Grip"],
    stress: ["pull"],
    notes: [
      "Do not run this within 48 hours of a hard hangboard or limit bouldering session. The fingers and elbows need the gap.",
      "If your bar work is fresh from climbing, drop block A to 3 sets and add a set to block C instead.",
    ],
    blocks: [
      {
        id: "fwl-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "prone-ytw", pres: "6 each position", note: "Bodyweight, activation only." },
        ],
      },
      {
        id: "fwl-a",
        tag: "A",
        title: "Primary Pull",
        kind: "straight",
        rounds: 5,
        rest: "2-3 min",
        minutes: 18,
        note: "Full range, dead hang to chin over bar. Add weight only when 5 clean reps are easy.",
        slots: [{ ex: "weighted-pullup", pres: "5 x 4-6", note: "Bodyweight pull-ups or barbell rows if you have no belt." }],
      },
      {
        id: "fwl-b",
        tag: "B",
        title: "Superset: Row + Scapular",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        slots: [
          { ex: "barbell-row", pres: "6-8 reps" },
          { ex: "prone-ytw", pres: "8 each position", note: "Light dumbbells, 2.5-5 lb is plenty." },
        ],
      },
      {
        id: "fwl-c",
        tag: "C",
        title: "Superset: Unilateral Row + Neutral Curl",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "db-row", pres: "8-10 per side" },
          { ex: "hammer-curl", pres: "10-12 reps" },
        ],
      },
      {
        id: "fwl-d",
        tag: "D",
        title: "Superset: Lat Stretch-Load + Elbow",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 9,
        slots: [
          { ex: "db-pullover", pres: "12 reps" },
          { ex: "reverse-curl", pres: "12-15 reps", note: "Deliberately light. The elbow is the point, not the forearm size." },
        ],
      },
      {
        id: "fwl-e",
        tag: "E",
        title: "Finisher: Grip & Trunk",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "dead-hang", pres: "25-30s" },
          { ex: "wrist-extension", pres: "15-20 reps" },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
    ],
  },

  {
    id: "fw-legs",
    name: "Legs & Core",
    category: "freeweights",
    minutes: [55, 70],
    tagline: "Squat, hinge, and the single-leg strength that high steps actually require.",
    equipment: ["Barbell + rack", "Dumbbells", "Bench or chair", "Step"],
    focus: ["Quads", "Glutes", "Hamstrings", "Trunk"],
    stress: ["legs"],
    notes: [
      "Climbers under-train legs and then wonder why rock-overs feel like a bench press. Single-leg work in block C is the highest-transfer item here.",
      "Schedule this the day before a rest day or a technique day, not before limit bouldering.",
    ],
    blocks: [
      {
        id: "fwg-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 9,
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
          { ex: "deep-squat-hold", pres: "45s" },
          { ex: "glute-bridge", pres: "10 per side" },
        ],
      },
      {
        id: "fwg-a",
        tag: "A",
        title: "Squat",
        kind: "straight",
        rounds: 4,
        rest: "2-3 min",
        minutes: 16,
        slots: [{ ex: "back-squat", pres: "4 x 5", note: "Goblet squat is a fine substitute; just go higher on reps, 4 x 10." }],
      },
      {
        id: "fwg-b",
        tag: "B",
        title: "Superset: Hinge + Calf",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        slots: [
          { ex: "rdl", pres: "8 reps" },
          { ex: "calf-raise", pres: "15-20 per side" },
        ],
      },
      {
        id: "fwg-c",
        tag: "C",
        title: "Superset: Single-Leg + Glute",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 13,
        note: "The most climbing-specific block in this plan. Do not rush the split squats.",
        slots: [
          { ex: "bulgarian-split-squat", pres: "8-10 per side" },
          { ex: "hip-thrust", pres: "12-15 reps" },
        ],
      },
      {
        id: "fwg-d",
        tag: "D",
        title: "Superset: High Step + Adductor",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 10,
        slots: [
          { ex: "high-step-up", pres: "10 per side" },
          { ex: "copenhagen", pres: "20-30s per side" },
        ],
      },
      {
        id: "fwg-e",
        tag: "E",
        title: "Finisher: Trunk",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "suitcase-carry", pres: "35s per side" },
          { ex: "hollow-hold", pres: "30s" },
          { ex: "bird-dog", pres: "8 per side" },
        ],
      },
    ],
  },

  {
    id: "fw-express",
    name: "Dumbbell Express",
    category: "freeweights",
    minutes: [40, 55],
    tagline: "One pair of dumbbells, all supersets, in and out in under an hour.",
    equipment: ["Dumbbells", "Chair or bench"],
    focus: ["Full body", "Time-efficient", "Minimal equipment"],
    stress: ["push", "pull", "legs"],
    notes: [
      "Everything here is paired. The only rest is between rounds, which is what keeps it under an hour.",
      "This is the fallback session for a week where climbing took priority. Two per week maintains strength without interfering.",
    ],
    blocks: [
      {
        id: "fwe-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "pulse-raiser", pres: "3 min" },
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "squat-to-stand", pres: "8 reps" },
          { ex: "scap-pushup", pres: "10 reps" },
        ],
      },
      {
        id: "fwe-a",
        tag: "A",
        title: "Superset: Squat + Row",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 14,
        slots: [
          { ex: "goblet-squat", pres: "10 reps" },
          { ex: "db-row", pres: "10 per side" },
        ],
      },
      {
        id: "fwe-b",
        tag: "B",
        title: "Superset: Press + Hinge",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 13,
        slots: [
          { ex: "db-floor-press", pres: "10 reps" },
          { ex: "rdl", pres: "10 reps", note: "Dumbbells, controlled. Feel the hamstrings, not the low back." },
        ],
      },
      {
        id: "fwe-c",
        tag: "C",
        title: "Superset: Overhead + Rear Delt",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "db-push-press", pres: "8 reps" },
          { ex: "rear-delt-fly", pres: "15 reps" },
        ],
      },
      {
        id: "fwe-d",
        tag: "D",
        title: "Circuit: Arms, Forearms, Core",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 9,
        note: "Minimal rest inside the round. Move.",
        slots: [
          { ex: "hammer-curl", pres: "12 reps" },
          { ex: "oh-tricep-ext", pres: "12 reps" },
          { ex: "wrist-extension", pres: "15 reps" },
          { ex: "plank", pres: "45s" },
        ],
      },
    ],
  },

  /* ============================ ELASTIC BANDS ============================ */
  {
    id: "bd-upper",
    name: "Band Upper Body",
    category: "bands",
    minutes: [45, 60],
    tagline: "Push and pull through a full range with a set of bands and a door anchor.",
    equipment: ["Resistance bands", "Door anchor", "Floor (warm-up only)"],
    focus: ["Chest", "Back", "Shoulders", "Arms"],
    stress: ["push", "pull"],
    notes: [
      "Bands load the opposite way to free weights: hardest at the end of the range, easiest at the start. That makes them excellent for shoulder and back work and mediocre for anything you want to load heavy.",
      "Change resistance by stepping further from the anchor or shortening your grip on the band, not by grinding out more reps.",
      "Rep ranges run higher than the barbell days on purpose. 12-15 is where bands do their best work.",
    ],
    blocks: [
      {
        id: "bdu-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "pulse-raiser", pres: "3 min" },
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "band-pull-apart", pres: "15 reps", note: "Lightest band you own." },
          { ex: "shoulder-pass-through", pres: "12 reps", note: "A band works here instead of a broomstick." },
        ],
      },
      {
        id: "bdu-a",
        tag: "A",
        title: "Superset: Press + Row",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 14,
        note: "The main pairing. Anchor at chest height and you can switch between them by turning around.",
        slots: [
          { ex: "band-chest-press", pres: "12-15 reps" },
          { ex: "band-row", pres: "12-15 reps" },
        ],
      },
      {
        id: "bdu-b",
        tag: "B",
        title: "Superset: Overhead + Pulldown",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "band-ohp", pres: "10-12 reps" },
          { ex: "band-pulldown", pres: "12-15 reps" },
        ],
      },
      {
        id: "bdu-c",
        tag: "C",
        title: "Superset: Delts",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 10,
        slots: [
          { ex: "band-lateral-raise", pres: "15 reps" },
          { ex: "band-face-pull", pres: "15 reps" },
        ],
      },
      {
        id: "bdu-d",
        tag: "D",
        title: "Superset: Arms",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 9,
        slots: [
          { ex: "band-curl", pres: "15 reps" },
          { ex: "band-pushdown", pres: "15 reps" },
        ],
      },
      {
        id: "bdu-e",
        tag: "E",
        title: "Finisher: Elbow & Trunk",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "band-wrist-ext", pres: "20 reps" },
          { ex: "band-finger-ext", pres: "25 reps" },
          { ex: "band-pallof", pres: "10 per side" },
        ],
      },
    ],
  },

  {
    id: "bd-legs",
    name: "Band Legs & Glutes",
    category: "bands",
    minutes: [35, 50],
    tagline: "Hip and glute work where bands genuinely outperform dumbbells.",
    equipment: ["Resistance bands", "Loop band", "Door anchor"],
    focus: ["Glutes", "Hamstrings", "Hip stability"],
    stress: ["legs"],
    notes: [
      "Loop bands beat dumbbells for glute medius work, which is the hip stability that stops your knee collapsing inward on a high step.",
      "Bands cannot load a squat heavily. Treat block A as volume and control, not as a strength lift.",
    ],
    blocks: [
      {
        id: "bdl-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 7,
        slots: [
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "deep-squat-hold", pres: "40s" },
          { ex: "band-monster-walk", pres: "10 steps each way" },
          { ex: "glute-bridge", pres: "10 per side" },
        ],
      },
      {
        id: "bdl-a",
        tag: "A",
        title: "Superset: Squat + Hinge",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 13,
        slots: [
          { ex: "band-squat", pres: "15 reps" },
          { ex: "band-rdl", pres: "15 reps" },
        ],
      },
      {
        id: "bdl-b",
        tag: "B",
        title: "Superset: Glute Drive + Hip",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "band-pull-through", pres: "15 reps" },
          { ex: "band-monster-walk", pres: "12 steps each way" },
        ],
      },
      {
        id: "bdl-c",
        tag: "C",
        title: "Superset: Single-Leg + Adductor",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        note: "Adductors and hip stability are what drop knees and heel hooks actually run on.",
        slots: [
          { ex: "reverse-lunge", pres: "12 per side", note: "Stand on the band for extra resistance." },
          { ex: "band-hip-adduction", pres: "15 per side" },
        ],
      },
      {
        id: "bdl-d",
        tag: "D",
        title: "Finisher",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 7,
        slots: [
          { ex: "band-calf-raise", pres: "20 per side" },
          { ex: "band-good-morning", pres: "15 reps" },
          { ex: "wall-sit", pres: "45s" },
        ],
      },
    ],
  },

  {
    id: "bd-express",
    name: "Band Full-Body Express",
    category: "bands",
    minutes: [25, 35],
    tagline: "One circuit, every pattern, packs in a jacket pocket. The travel strength session.",
    equipment: ["Resistance bands", "Door anchor"],
    focus: ["Full body", "Travel", "Minimal time"],
    stress: ["push", "pull", "legs"],
    notes: [
      "Three rounds of six movements. The only rest is between rounds, which is what keeps it near half an hour.",
      "Pairs with the standing sessions on a travel week: this on hotel days, the standing reset on transit days.",
    ],
    blocks: [
      {
        id: "bde-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "standing-march", pres: "60s" },
          { ex: "band-pull-apart", pres: "15 reps" },
          { ex: "squat-to-stand", pres: "8 reps" },
          { ex: "arm-circles", pres: "10 each way" },
        ],
      },
      {
        id: "bde-a",
        tag: "A",
        title: "Circuit: Full Body",
        kind: "circuit",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 19,
        note: "Straight through all six, then rest. Keep the transitions quick.",
        slots: [
          { ex: "band-squat", pres: "15 reps" },
          { ex: "band-row", pres: "15 reps" },
          { ex: "band-rdl", pres: "15 reps" },
          { ex: "band-chest-press", pres: "15 reps" },
          { ex: "band-ohp", pres: "12 reps" },
          { ex: "band-pallof", pres: "10 per side" },
        ],
      },
      {
        id: "bde-b",
        tag: "B",
        title: "Finisher",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 5,
        slots: [
          { ex: "band-face-pull", pres: "20 reps" },
          { ex: "band-finger-ext", pres: "25 reps" },
        ],
      },
    ],
  },

  {
    id: "bd-prehab",
    name: "Band Shoulder & Elbow Prehab",
    category: "bands",
    minutes: [15, 22],
    tagline: "Twenty minutes of the antagonist work that keeps climbing elbows and shoulders quiet.",
    equipment: ["Light resistance band", "Door anchor"],
    focus: ["Rotator cuff", "Lower traps", "Elbow health"],
    notes: [
      "The highest return-per-minute session here, and the one most likely to get skipped. Climbing is almost entirely pulling and closing; every movement in this plan does the opposite.",
      "Everything is deliberately light. If a set feels like strength work, the band is too heavy.",
      "Run it twice a week on rest days, or tack it onto the end of a climbing session.",
    ],
    blocks: [
      {
        id: "bdp-a",
        tag: "A",
        title: "Circuit: Cuff & Scapula",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 7,
        slots: [
          { ex: "band-pull-apart", pres: "20 reps" },
          { ex: "shoulder-er", pres: "15 per side", note: "Band version. Elbow glued to the ribs." },
          { ex: "band-y-raise", pres: "12 reps" },
        ],
      },
      {
        id: "bdp-b",
        tag: "B",
        title: "Circuit: Posterior Chain of the Shoulder",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 7,
        slots: [
          { ex: "band-face-pull", pres: "15 reps" },
          { ex: "band-straight-arm-pulldown", pres: "15 reps" },
          { ex: "band-rear-fly", pres: "15 reps" },
        ],
      },
      {
        id: "bdp-c",
        tag: "C",
        title: "Circuit: Forearm & Elbow",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 5,
        slots: [
          { ex: "band-finger-ext", pres: "25 reps" },
          { ex: "band-wrist-ext", pres: "20 reps" },
          { ex: "forearm-flush", pres: "60s" },
        ],
      },
    ],
  },

  /* ============================= BODYWEIGHT ============================= */
  {
    id: "bw-push",
    name: "Bodyweight Push & Core",
    category: "bodyweight",
    minutes: [45, 55],
    tagline: "Floor and one chair. Pressing volume and trunk tension, no equipment.",
    equipment: ["Floor", "One sturdy chair"],
    focus: ["Chest", "Shoulders", "Triceps", "Core"],
    stress: ["push"],
    notes: [
      "With no external load, difficulty comes from leverage and tempo. Elevating the feet or slowing the lowering is how you progress, not adding reps forever.",
      "Check the chair is stable before block A. A dining chair works; an office chair does not.",
    ],
    blocks: [
      {
        id: "bwp-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 8,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "worlds-greatest-stretch", pres: "4 per side" },
          { ex: "pushup", pres: "8 reps", note: "Knees down if needed. Primer only." },
        ],
      },
      {
        id: "bwp-a",
        tag: "A",
        title: "Superset: Decline Push + Dip",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 14,
        note: "Feet on the chair for the push-up, hands on the chair for the dip. No repositioning time.",
        slots: [
          { ex: "decline-pushup", pres: "8-12 reps" },
          { ex: "chair-dip", pres: "10-15 reps" },
        ],
      },
      {
        id: "bwp-b",
        tag: "B",
        title: "Superset: Vertical Press + Hollow",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "pike-pushup", pres: "6-10 reps", note: "Feet on the chair to make it a near-handstand press." },
          { ex: "hollow-hold", pres: "25-40s" },
        ],
      },
      {
        id: "bwp-c",
        tag: "C",
        title: "Superset: Tempo / Unilateral + Side Plank",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "tempo-pushup", pres: "6 reps @ 3s down", note: "Swap for archer push-ups once tempo reps are easy." },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
      {
        id: "bwp-d",
        tag: "D",
        title: "Circuit: Shoulder Control & Core",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 10,
        slots: [
          { ex: "shoulder-taps", pres: "20 taps" },
          { ex: "ab-rollout", pres: "8-10 reps", note: "Socks on a hard floor, or a towel." },
          { ex: "reverse-snow-angel", pres: "15 reps" },
        ],
      },
      {
        id: "bwp-e",
        tag: "E",
        title: "Finisher",
        kind: "straight",
        rounds: 3,
        rest: "45s",
        minutes: 4,
        slots: [{ ex: "wall-handstand", pres: "3 x 20-40s", note: "Or a feet-on-chair pike hold if the wall is not an option." }],
      },
    ],
  },

  {
    id: "bw-pull",
    name: "Bodyweight Pull & Posterior",
    category: "bodyweight",
    minutes: [40, 50],
    tagline: "The honest version of bodyweight pulling: scapular control, posterior chain, isometrics.",
    equipment: ["Floor", "One sturdy chair", "Towel", "Socks or sliders"],
    focus: ["Upper back", "Posterior chain", "Shoulder health"],
    stress: ["pull"],
    notes: [
      "Straight talk: without a bar, rings or a door pull-up bar you cannot meaningfully load a vertical pull. This session trains scapular control, the posterior chain and isometric pulling instead.",
      "If bodyweight days are a regular part of your week, a $25 doorway pull-up bar changes what is possible here more than any other purchase.",
      "For a climber this session is still worth running: the lower trap and rear delt work is exactly what heavy pulling neglects.",
    ],
    blocks: [
      {
        id: "bwl-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 8,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "thoracic-rotation", pres: "6 per side" },
          { ex: "prone-ytw", pres: "5 each position" },
          { ex: "finger-rolls", pres: "20 reps" },
        ],
      },
      {
        id: "bwl-a",
        tag: "A",
        title: "Superset: Scapular Endurance",
        kind: "superset",
        rounds: 4,
        rest: "60s between rounds",
        minutes: 12,
        note: "Both of these look trivial and are not. Go slow enough that round 4 is hard.",
        slots: [
          { ex: "prone-ytw", pres: "8 each position" },
          { ex: "reverse-snow-angel", pres: "15 reps" },
        ],
      },
      {
        id: "bwl-b",
        tag: "B",
        title: "Superset: Lat Pull + Isometric Row",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 11,
        slots: [
          { ex: "floor-lat-pull", pres: "8-12 reps" },
          { ex: "towel-row-iso", pres: "6 x 10s pulls", note: "Towel around a door handle, lean back and pull hard." },
        ],
      },
      {
        id: "bwl-c",
        tag: "C",
        title: "Superset: Hinge + Glute",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "rdl", pres: "12 per side", note: "Single-leg, bodyweight. Slow, reach the floor with the fingertips." },
          { ex: "glute-bridge", pres: "12 per side" },
        ],
      },
      {
        id: "bwl-d",
        tag: "D",
        title: "Circuit: Extension & Stability",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 9,
        slots: [
          { ex: "superman", pres: "30s hold" },
          { ex: "bird-dog", pres: "8 per side" },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
    ],
  },

  {
    id: "bw-legs",
    name: "Bodyweight Legs",
    category: "bodyweight",
    minutes: [40, 50],
    tagline: "Single-leg strength, knee control and hip range. Chair does most of the work.",
    equipment: ["Floor", "One sturdy chair", "Step (optional)"],
    focus: ["Quads", "Glutes", "Single-leg", "Hip mobility"],
    stress: ["legs"],
    notes: [
      "Bodyweight legs get hard through unilateral loading and tempo, not volume. If a set of 20 feels easy, move to the harder progression instead of doing 30.",
    ],
    blocks: [
      {
        id: "bwg-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 8,
        slots: [
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "squat-to-stand", pres: "8 reps" },
          { ex: "deep-squat-hold", pres: "40s" },
          { ex: "glute-bridge", pres: "10 per side" },
        ],
      },
      {
        id: "bwg-a",
        tag: "A",
        title: "Superset: Tempo Squat + Assisted Pistol",
        kind: "superset",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 14,
        slots: [
          { ex: "goblet-squat", pres: "15 reps @ 3s down", note: "No weight: bodyweight squat, arms forward, 3 second lowering." },
          { ex: "pistol-progression", pres: "8 per side" },
        ],
      },
      {
        id: "bwg-b",
        tag: "B",
        title: "Superset: Split Squat + Single-Leg Glute",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        slots: [
          { ex: "bulgarian-split-squat", pres: "10 per side", note: "Rear foot on the chair, bodyweight only." },
          { ex: "glute-bridge", pres: "12 per side", note: "Heel on the chair to increase range." },
        ],
      },
      {
        id: "bwg-c",
        tag: "C",
        title: "Superset: Lunge + Calf",
        kind: "superset",
        rounds: 3,
        rest: "60s between rounds",
        minutes: 10,
        slots: [
          { ex: "reverse-lunge", pres: "12 per side" },
          { ex: "calf-raise", pres: "15-20 per side" },
        ],
      },
      {
        id: "bwg-d",
        tag: "D",
        title: "Circuit: Endurance & Hips",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "wall-sit", pres: "45-60s" },
          { ex: "copenhagen", pres: "20-30s per side" },
          { ex: "step-down", pres: "8 per side" },
          { ex: "high-step-drill", pres: "8 per side" },
        ],
      },
    ],
  },

  {
    id: "bw-express",
    name: "Bodyweight Express Circuit",
    category: "bodyweight",
    minutes: [25, 35],
    tagline: "Hotel-room session. Six movements, 40 seconds on, 20 off, four rounds.",
    equipment: ["Floor", "One chair"],
    focus: ["Full body", "Travel", "Minimal time"],
    stress: ["push", "legs"],
    notes: [
      "Timed intervals, not rep targets. Use the interval timer in the session: 40s work, 20s rest.",
      "Four rounds is roughly 24 minutes of work. Three rounds is a legitimate short day.",
    ],
    blocks: [
      {
        id: "bwx-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "squat-to-stand", pres: "8 reps" },
          { ex: "scap-pushup", pres: "10 reps" },
        ],
      },
      {
        id: "bwx-a",
        tag: "A",
        title: "Circuit: 40s On / 20s Off",
        kind: "interval",
        rounds: 4,
        rest: "90s between rounds",
        minutes: 26,
        note: "Run the interval timer. One pass through all six is a round.",
        interval: { work: 40, rest: 20, reps: 6, setRest: 90, sets: 4 },
        slots: [
          { ex: "goblet-squat", pres: "40s", note: "Bodyweight, continuous." },
          { ex: "decline-pushup", pres: "40s" },
          { ex: "reverse-lunge", pres: "40s alternating" },
          { ex: "chair-dip", pres: "40s" },
          { ex: "reverse-snow-angel", pres: "40s" },
          { ex: "hollow-hold", pres: "40s" },
        ],
      },
      {
        id: "bwx-b",
        tag: "B",
        title: "Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        slots: [
          { ex: "hamstring-stretch", pres: "45s per side" },
          { ex: "pigeon-stretch", pres: "60s per side" },
        ],
      },
    ],
  },

  /* =========================== CLIMBING GYM =========================== */
  {
    id: "cg-max",
    name: "Hangboard & Limit Boulders",
    category: "gym",
    minutes: [100, 120],
    tagline: "Max hangs, then limit bouldering, then antagonist work. The hardest day of the week.",
    equipment: ["Climbing wall", "Hangboard", "Free weights"],
    focus: ["Finger strength", "Max power", "Recruitment"],
    stress: ["fingers", "pull"],
    notes: [
      "Prerequisite: roughly a year of consistent climbing before loading a hangboard. Tendons adapt far slower than muscle.",
      "Never start hangboarding cold, and never on consecutive days. Two finger-intensive sessions per week is the ceiling for most people.",
      "Any sharp, hot or localized pain in a single finger ends the finger work for the day. No exceptions.",
      "Order matters: fingers and power come first, while the nervous system is fresh. Strength work last.",
    ],
    blocks: [
      {
        id: "cgm-w",
        tag: "W",
        title: "Warm-Up (do not skip)",
        kind: "circuit",
        rounds: 1,
        minutes: 18,
        note: "18 minutes. This is the price of admission for max hangs.",
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "easy-climbing", pres: "4-5 problems" },
          { ex: "progressive-hangs", pres: "3 x 10-15s" },
          { ex: "moderate-climbing", pres: "2 problems" },
        ],
      },
      {
        id: "cgm-a",
        tag: "A",
        title: "Hangboard: Max Hangs",
        kind: "interval",
        rounds: 5,
        rest: "2-3 min between sets",
        minutes: 20,
        note: "Half crimp, 20mm edge. Effort where you could hold 2-3 seconds longer, never to failure.",
        interval: { work: 10, rest: 0, reps: 1, setRest: 150, sets: 5 },
        slots: [{ ex: "max-hang", pres: "5 x 7-10s", note: "Add or remove weight to keep every set at the same effort." }],
      },
      {
        id: "cgm-b",
        tag: "B",
        title: "Limit Bouldering",
        kind: "straight",
        rounds: 8,
        rest: "3-5 min between attempts",
        minutes: 35,
        note: "2-3 problems at or just past your limit. When attempts visibly degrade, the block is over even if time remains.",
        unit: "Attempts",
        slots: [{ ex: "limit-boulder", pres: "8-10 attempts" }],
      },
      {
        id: "cgm-c",
        tag: "C",
        title: "Superset: Weighted Pull + Overhead",
        kind: "superset",
        rounds: 3,
        rest: "2 min between rounds",
        minutes: 12,
        slots: [
          { ex: "weighted-pullup", pres: "4-5 reps" },
          { ex: "ohp", pres: "8 reps", note: "Dumbbells. Antagonist work, moderate load." },
        ],
      },
      {
        id: "cgm-d",
        tag: "D",
        title: "Superset: Tension Core + Press",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "front-lever-tuck", pres: "6-8s hold" },
          { ex: "pushup", pres: "12-15 reps" },
        ],
      },
      {
        id: "cgm-e",
        tag: "E",
        title: "Finisher: Elbow & Cool-Down",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 10,
        slots: [
          { ex: "wrist-extension", pres: "15-20 reps" },
          { ex: "band-finger-ext", pres: "20 reps" },
          { ex: "shoulder-er", pres: "12 per side" },
          { ex: "forearm-flush", pres: "60s" },
        ],
      },
    ],
  },

  {
    id: "cg-power-endurance",
    name: "Power Endurance 4x4s",
    category: "gym",
    minutes: [85, 100],
    tagline: "Four flash-grade boulders back to back, four times. Then pulling and core.",
    equipment: ["Climbing wall", "Pull-up bar", "Free weights"],
    focus: ["Power endurance", "Lactate tolerance", "Mental grit"],
    stress: ["fingers", "pull"],
    notes: [
      "This session is supposed to feel awful by set 3. That is the training effect, not a sign you picked the wrong problems.",
      "Run it at most once a week, and not within 48 hours of a max strength day.",
      "Pick the four problems and check they are free before you start. Waiting for a wall between problems kills the stimulus.",
    ],
    blocks: [
      {
        id: "cgp-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 16,
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "easy-climbing", pres: "4 problems" },
          { ex: "moderate-climbing", pres: "2-3 problems" },
          { ex: "campus-recruit", pres: "2 pulls" },
        ],
      },
      {
        id: "cgp-a",
        tag: "A",
        title: "4 x 4s",
        kind: "straight",
        rounds: 4,
        rest: "4-5 min between sets",
        minutes: 35,
        note: "Four problems at your comfortable flash grade, climbed back to back. Only the walk between them is rest. That is one set.",
        unit: "Sets",
        slots: [{ ex: "four-by-four", pres: "4 sets of 4 problems" }],
      },
      {
        id: "cgp-b",
        tag: "B",
        title: "Superset: Pull + Push",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        note: "Fingers are cooked by now, so this is deliberately bar and bodyweight work, not hangboard.",
        slots: [
          { ex: "pullup", pres: "8-10 reps" },
          { ex: "dip-bars", pres: "10-12 reps" },
        ],
      },
      {
        id: "cgp-c",
        tag: "C",
        title: "Circuit: Core",
        kind: "circuit",
        rounds: 3,
        rest: "60s",
        minutes: 10,
        slots: [
          { ex: "hanging-knee-raise", pres: "10 reps" },
          { ex: "plank", pres: "45s" },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
      {
        id: "cgp-d",
        tag: "D",
        title: "Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "cool-down-climb", pres: "5 min" },
          { ex: "forearm-flush", pres: "90s" },
          { ex: "doorway-chest", pres: "45s each" },
        ],
      },
    ],
  },

  {
    id: "cg-repeaters",
    name: "Repeaters & Volume",
    category: "gym",
    minutes: [90, 105],
    tagline: "Hangboard repeaters across two grip types, then high-mileage easy climbing.",
    equipment: ["Climbing wall", "Hangboard", "Free weights"],
    focus: ["Finger strength-endurance", "Grip variety", "Mileage"],
    stress: ["fingers", "pull"],
    notes: [
      "Repeaters are submaximal by design: 7 seconds on, 3 off, six times. Load for RPE 7-8, not failure.",
      "Two grip positions in one session is enough. Half crimp first while you are fresh, then open hand.",
      "If grip position degrades mid-set, stop that set. A sloppy hang trains sloppy fingers.",
    ],
    blocks: [
      {
        id: "cgr-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 16,
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "easy-climbing", pres: "4 problems" },
          { ex: "progressive-hangs", pres: "3 x 10-15s" },
          { ex: "moderate-climbing", pres: "2 problems" },
        ],
      },
      {
        id: "cgr-a",
        tag: "A",
        title: "Repeaters: Half Crimp",
        kind: "interval",
        rounds: 3,
        rest: "3 min between sets",
        minutes: 14,
        note: "7s on / 3s off x 6 reps = one set. Timer is built in.",
        interval: { work: 7, rest: 3, reps: 6, setRest: 180, sets: 3 },
        slots: [{ ex: "repeater-hang", pres: "3 sets x 6 reps", note: "20mm edge, half crimp, thumb off." }],
      },
      {
        id: "cgr-b",
        tag: "B",
        title: "Repeaters: Open Hand / 3-Finger Drag",
        kind: "interval",
        rounds: 3,
        rest: "3 min between sets",
        minutes: 14,
        note: "Same protocol, lighter load. Open hand always feels weaker than half crimp.",
        interval: { work: 7, rest: 3, reps: 6, setRest: 180, sets: 3 },
        slots: [{ ex: "open-hand-hang", pres: "3 sets x 6 reps" }],
      },
      {
        id: "cgr-c",
        tag: "C",
        title: "Volume Climbing",
        kind: "straight",
        rounds: 1,
        minutes: 30,
        note: "Mileage, not difficulty. Rotate wall angles every few problems.",
        slots: [
          { ex: "volume-climbing", pres: "25-30 min" },
          { ex: "downclimbing", pres: "on every easy problem" },
        ],
      },
      {
        id: "cgr-d",
        tag: "D",
        title: "Superset: Row + Press",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 11,
        slots: [
          { ex: "barbell-row", pres: "10 reps" },
          { ex: "ohp", pres: "10 reps" },
        ],
      },
      {
        id: "cgr-e",
        tag: "E",
        title: "Finisher & Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "wrist-extension", pres: "20 reps" },
          { ex: "band-finger-ext", pres: "25 reps" },
          { ex: "forearm-flush", pres: "90s" },
        ],
      },
    ],
  },

  {
    id: "cg-technique",
    name: "Technique & Movement Skills",
    category: "gym",
    minutes: [60, 80],
    tagline: "Drill-based session on easy terrain. Low intensity, high attention. Use it between hard days.",
    equipment: ["Climbing wall", "Hangboard (light)", "Free weights (light)"],
    focus: ["Footwork", "Body positioning", "Efficiency", "Active recovery"],
    notes: [
      "Everything here happens 2-3 grades below your limit. The moment a problem is hard enough to demand effort, the drill stops working.",
      "This is the session that actually raises your ceiling between strength blocks, and the one most people skip because it does not feel like training.",
      "Pick two or three drills per session, not all of them. Depth beats breadth.",
    ],
    blocks: [
      {
        id: "cgt-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 12,
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "finger-rolls", pres: "25 reps" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "high-step-drill", pres: "8 per side" },
          { ex: "easy-climbing", pres: "3-4 problems" },
        ],
      },
      {
        id: "cgt-a",
        tag: "A",
        title: "Footwork Drills",
        kind: "circuit",
        rounds: 1,
        minutes: 18,
        note: "Easy problems only. Zero pump by design.",
        slots: [
          { ex: "silent-feet", pres: "3 problems" },
          { ex: "hover-drill", pres: "2 problems" },
          { ex: "one-touch", pres: "2 problems" },
        ],
      },
      {
        id: "cgt-b",
        tag: "B",
        title: "Body Position Drills",
        kind: "circuit",
        rounds: 1,
        minutes: 18,
        slots: [
          { ex: "straight-arm-drill", pres: "3 x 2 min traverse" },
          { ex: "flag-drill", pres: "3 problems" },
          { ex: "downclimbing", pres: "3 problems up and down" },
        ],
      },
      {
        id: "cgt-c",
        tag: "C",
        title: "Light Hangboard (optional)",
        kind: "interval",
        rounds: 3,
        rest: "3 min between sets",
        minutes: 12,
        note: "RPE 6. Skip this entirely if the session is meant as recovery.",
        interval: { work: 7, rest: 3, reps: 6, setRest: 180, sets: 3 },
        slots: [{ ex: "repeater-hang", pres: "3 sets x 6 reps", note: "Noticeably easy. If it feels like work, drop the load." }],
      },
      {
        id: "cgt-d",
        tag: "D",
        title: "Superset: Balance Work",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "pullup", pres: "6 reps" },
          { ex: "pushup", pres: "12 reps" },
          { ex: "dead-bug", pres: "8 per side" },
        ],
      },
      {
        id: "cgt-e",
        tag: "E",
        title: "Mobility Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "pigeon-stretch", pres: "60s per side" },
          { ex: "doorway-chest", pres: "45s each" },
          { ex: "forearm-flush", pres: "60s" },
        ],
      },
    ],
  },

  /* ============================== SOCCER ============================== */
  {
    id: "sc-prevention",
    name: "Injury Prevention",
    category: "soccer",
    minutes: [20, 28],
    tagline: "Hamstrings, groin and landing control. The best-evidenced session in this app.",
    equipment: ["Floor", "Couch or partner to anchor the ankles", "Ball or towel"],
    focus: ["Hamstrings", "Adductors", "Knee control"],
    stress: ["legs"],
    notes: [
      "Hamstring and groin strains are the two most common non-contact injuries in amateur soccer, and both respond to specific eccentric and isometric work rather than to general fitness.",
      "The evidence here is unusually strong for a training claim. Meta-analyses of the Nordic hamstring exercise in football squads report roughly a halving of hamstring injury rates; trials of the Copenhagen adduction exercise report a large reduction in groin problems; structured warm-up programmes of this shape (the FIFA 11+ family) report around a third fewer injuries overall. Figures vary by study and adherence, so treat them as the right order of magnitude rather than precise numbers.",
      "Twice a week, year round. Adherence is the whole game: a programme you run in preseason and abandon in October does nothing for you in October.",
      "Expect to be sore after the first two or three Nordic sessions. Start at the low end of the reps.",
    ],
    blocks: [
      {
        id: "scp-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "pulse-raiser", pres: "3 min" },
          { ex: "groiners", pres: "10 reps" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "glute-bridge", pres: "10 per side" },
        ],
      },
      {
        id: "scp-a",
        tag: "A",
        title: "Circuit: Hamstring & Groin",
        kind: "circuit",
        rounds: 2,
        rest: "60s",
        minutes: 9,
        note: "The two exercises with the strongest evidence behind them. Do not substitute these.",
        slots: [
          { ex: "nordic-curl", pres: "4-6 reps" },
          { ex: "copenhagen", pres: "25-30s per side" },
          { ex: "groin-squeeze", pres: "5 x 10s" },
        ],
      },
      {
        id: "scp-b",
        tag: "B",
        title: "Circuit: Balance & Hip Control",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 7,
        slots: [
          { ex: "single-leg-rdl-balance", pres: "8 per side" },
          { ex: "single-leg-balance", pres: "45s per side" },
          { ex: "side-plank", pres: "30s per side" },
        ],
      },
      {
        id: "scp-c",
        tag: "C",
        title: "Circuit: Landing & Braking",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 6,
        note: "Non-contact knee injuries happen on landings and cuts. This block rehearses both slowly.",
        slots: [
          { ex: "lateral-bound", pres: "6 per side" },
          { ex: "deceleration-drill", pres: "6 reps" },
          { ex: "pogo-hops", pres: "20 contacts" },
        ],
      },
    ],
  },

  {
    id: "sc-strength",
    name: "Soccer Strength & Power",
    category: "soccer",
    minutes: [50, 65],
    tagline: "Squat, single-leg and jump work, with the hamstring insurance built in.",
    equipment: ["Barbell + rack", "Dumbbells", "Box or bench"],
    focus: ["Legs", "Power", "Rotational core"],
    stress: ["legs"],
    notes: [
      "Power work goes before strength work, and both go before anything that fatigues you. Jumping on tired legs trains nothing and hurts more.",
      "Do not run this within 48 hours of a match or a hard speed session. The legs need to be fresh for both.",
      "Block E is rotational. Every shot, long pass and change of direction is a rotation, and almost nobody trains it.",
    ],
    blocks: [
      {
        id: "scs-w",
        tag: "W",
        title: "Warm-Up",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "groiners", pres: "10 reps" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
          { ex: "a-skip", pres: "2 x 20 m" },
          { ex: "deep-squat-hold", pres: "40s" },
        ],
      },
      {
        id: "scs-a",
        tag: "A",
        title: "Power",
        kind: "superset",
        rounds: 4,
        rest: "2 min between rounds",
        minutes: 12,
        note: "Fresh legs only. Stop the block the moment a jump looks worse than the one before it.",
        slots: [
          { ex: "box-jump", pres: "5 reps" },
          { ex: "broad-jump", pres: "4 reps" },
        ],
      },
      {
        id: "scs-b",
        tag: "B",
        title: "Squat",
        kind: "straight",
        rounds: 4,
        rest: "2-3 min",
        minutes: 14,
        slots: [{ ex: "back-squat", pres: "4 x 5", note: "Goblet squat at 4 x 10 if you have no rack." }],
      },
      {
        id: "scs-c",
        tag: "C",
        title: "Superset: Single-Leg + Hamstring",
        kind: "superset",
        rounds: 3,
        rest: "90s between rounds",
        minutes: 12,
        slots: [
          { ex: "bulgarian-split-squat", pres: "8 per side" },
          { ex: "nordic-curl", pres: "4-6 reps" },
        ],
      },
      {
        id: "scs-d",
        tag: "D",
        title: "Superset: Step-Up + Adductor",
        kind: "superset",
        rounds: 3,
        rest: "75s between rounds",
        minutes: 10,
        slots: [
          { ex: "high-step-up", pres: "10 per side" },
          { ex: "copenhagen", pres: "25s per side" },
        ],
      },
      {
        id: "scs-e",
        tag: "E",
        title: "Circuit: Rotational Core",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 8,
        slots: [
          { ex: "wood-chop", pres: "12 per side" },
          { ex: "russian-twist", pres: "20 touches" },
          { ex: "plank", pres: "45s" },
        ],
      },
    ],
  },

  {
    id: "sc-speed",
    name: "Speed & Agility",
    category: "soccer",
    minutes: [40, 50],
    tagline: "Accelerations, cuts and braking. Short efforts, long rests, no conditioning.",
    equipment: ["Open space, about 30 m", "3-6 cones or markers"],
    focus: ["Acceleration", "Change of direction", "Deceleration"],
    stress: ["legs"],
    notes: [
      "This is not a fitness session, and treating it like one ruins it. Every rep is maximal, and the rest between reps is long enough that the next one is just as fast.",
      "If your times or your movement quality drop off, the session is over regardless of how much time is left.",
      "Full warm-up first. Cold hamstrings and maximal sprinting is the single most reliable way to tear one.",
    ],
    blocks: [
      {
        id: "scd-w",
        tag: "W",
        title: "Warm-Up (do not skip)",
        kind: "circuit",
        rounds: 1,
        minutes: 12,
        note: "Twelve minutes. Sprinting is the highest-risk thing in this app after max hangs.",
        slots: [
          { ex: "pulse-raiser", pres: "4 min" },
          { ex: "groiners", pres: "10 reps" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "a-skip", pres: "2 x 20 m" },
          { ex: "carioca", pres: "2 x 20 m" },
          { ex: "accelerations", pres: "3 reps at 70-80%" },
        ],
      },
      {
        id: "scd-a",
        tag: "A",
        title: "Accelerations",
        kind: "straight",
        rounds: 6,
        rest: "60-90s between reps",
        minutes: 10,
        unit: "Reps",
        slots: [{ ex: "accelerations", pres: "6 x 20-30 m", note: "Full effort. Walk back slowly between reps." }],
      },
      {
        id: "scd-b",
        tag: "B",
        title: "Change of Direction",
        kind: "straight",
        rounds: 6,
        rest: "60s between reps",
        minutes: 9,
        unit: "Reps",
        slots: [{ ex: "pro-agility", pres: "6 reps", note: "Alternate which side you open to." }],
      },
      {
        id: "scd-c",
        tag: "C",
        title: "Circuit: Movement Patterns",
        kind: "circuit",
        rounds: 3,
        rest: "60s",
        minutes: 9,
        slots: [
          { ex: "lateral-shuffle", pres: "15 m each way" },
          { ex: "backpedal", pres: "15 m" },
          { ex: "deceleration-drill", pres: "4 reps" },
        ],
      },
      {
        id: "scd-d",
        tag: "D",
        title: "Cool-Down",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "standing-forward-fold", pres: "60s" },
          { ex: "standing-hip-flexor", pres: "45s per side" },
          { ex: "pigeon-stretch", pres: "60s per side" },
        ],
      },
    ],
  },

  {
    id: "sc-skills",
    name: "Ball Skills & Touch",
    category: "soccer",
    minutes: [30, 45],
    tagline: "Solo technical work. A ball, a wall, and a few markers.",
    equipment: ["Ball", "A wall", "5-6 cones or markers"],
    focus: ["First touch", "Close control", "Weak foot"],
    notes: [
      "Touch is the one thing you can train alone, indoors, at any fitness level, with no injury risk. It is also the first thing that decays between seasons.",
      "Eyes up as often as possible. Control you can only perform while staring at the ball does not survive a match.",
      "The weak foot block is the highest-value ten minutes here for most amateur players, and the least enjoyable.",
    ],
    blocks: [
      {
        id: "sck-a",
        tag: "1",
        title: "Juggling",
        kind: "straight",
        rounds: 1,
        minutes: 5,
        slots: [{ ex: "juggling", pres: "5 min" }],
      },
      {
        id: "sck-b",
        tag: "2",
        title: "Circuit: Ball Mastery",
        kind: "circuit",
        rounds: 3,
        rest: "30s",
        minutes: 8,
        slots: [
          { ex: "sole-rolls", pres: "30s each variation" },
          { ex: "cone-dribble", pres: "2 passes" },
        ],
      },
      {
        id: "sck-c",
        tag: "3",
        title: "Circuit: Wall Work",
        kind: "circuit",
        rounds: 3,
        rest: "45s",
        minutes: 12,
        note: "Two-touch first, then one-touch once the weight of pass is consistent.",
        slots: [
          { ex: "wall-pass", pres: "20 passes two-touch" },
          { ex: "wall-pass", pres: "20 passes one-touch" },
          { ex: "first-touch-wall", pres: "15 receptions" },
        ],
      },
      {
        id: "sck-d",
        tag: "4",
        title: "Weak Foot Only",
        kind: "straight",
        rounds: 1,
        minutes: 10,
        slots: [{ ex: "weak-foot-drill", pres: "10 min" }],
      },
      {
        id: "sck-e",
        tag: "5",
        title: "Finish",
        kind: "straight",
        rounds: 1,
        minutes: 4,
        slots: [{ ex: "juggling", pres: "4 min", note: "Beat the number you set at the start." }],
      },
    ],
  },

  {
    id: "sc-matchday",
    name: "Match Day Warm-Up",
    category: "soccer",
    minutes: [20, 26],
    tagline: "Raise, mobilise, potentiate, touch the ball. Finish five minutes before kick-off.",
    equipment: ["Ball", "Open space"],
    focus: ["Match readiness", "Injury prevention", "First touch"],
    notes: [
      "The order is deliberate: general movement, then mobility, then progressively faster efforts, then the ball. Ramping intensity is what actually prepares tissue; static stretching beforehand does not, and may briefly reduce power output.",
      "Finish close to kick-off. A warm-up that ends twenty minutes early is a warm-up you no longer have.",
      "In cold weather, add a layer rather than cutting the first block short.",
    ],
    blocks: [
      {
        id: "scm-a",
        tag: "1",
        title: "Raise",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "pulse-raiser", pres: "4 min", note: "Easy jog, building to a comfortable pace." },
          { ex: "standing-march", pres: "60s" },
        ],
      },
      {
        id: "scm-b",
        tag: "2",
        title: "Mobilise & Activate",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "groiners", pres: "10 reps" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "glute-bridge", pres: "10 per side" },
          { ex: "copenhagen", pres: "20s per side" },
        ],
      },
      {
        id: "scm-c",
        tag: "3",
        title: "Potentiate",
        kind: "circuit",
        rounds: 2,
        rest: "45s",
        minutes: 7,
        note: "Build the speed across the two rounds. The last accelerations should be near full effort.",
        slots: [
          { ex: "a-skip", pres: "20 m" },
          { ex: "carioca", pres: "20 m each way" },
          { ex: "lateral-bound", pres: "4 per side" },
          { ex: "accelerations", pres: "2 reps" },
        ],
      },
      {
        id: "scm-d",
        tag: "4",
        title: "Ball",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "juggling", pres: "2 min" },
          { ex: "wall-pass", pres: "20 passes", note: "Or short passing with a teammate." },
          { ex: "first-touch-wall", pres: "10 receptions" },
        ],
      },
    ],
  },

  /* =========================== STANDING ONLY =========================== */
  {
    id: "st-gate",
    name: "Gate Area Reset",
    category: "standing",
    minutes: [8, 12],
    tagline: "Ten minutes standing in one square metre. Nothing touches the floor.",
    equipment: ["Nothing", "A wall or pillar helps, optional"],
    focus: ["Circulation", "Hips", "Spine"],
    notes: [
      "Built for a gate area: no mat, no chair, no kneeling, and nothing that looks strange enough to draw attention.",
      "Everything is standing, so a wall or pillar is only ever for balance. Skip it and hold a rail, or just wobble.",
      "Worth doing before a flight, not only after. Going in already loose beats trying to undo it later.",
    ],
    blocks: [
      {
        id: "stg-a",
        tag: "1",
        title: "Get the blood moving",
        kind: "circuit",
        rounds: 1,
        minutes: 3,
        note: "Sitting still is the problem. This is the part that actually addresses it.",
        slots: [
          { ex: "standing-march", pres: "60s" },
          { ex: "calf-pump", pres: "25 reps" },
          { ex: "ankle-circles", pres: "10 each direction" },
        ],
      },
      {
        id: "stg-b",
        tag: "2",
        title: "Spine and shoulders",
        kind: "circuit",
        rounds: 1,
        minutes: 3,
        slots: [
          { ex: "shoulder-rolls", pres: "10 each way" },
          { ex: "chin-tuck", pres: "10 reps" },
          { ex: "standing-twist", pres: "8 per side" },
          { ex: "overhead-side-reach", pres: "25s per side" },
        ],
      },
      {
        id: "stg-c",
        tag: "3",
        title: "Hips and legs",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "standing-hip-flexor", pres: "45s per side" },
          { ex: "standing-figure-four", pres: "45s per side" },
          { ex: "standing-forward-fold", pres: "45s" },
          { ex: "standing-quad-stretch", pres: "30s per side" },
        ],
      },
    ],
  },

  {
    id: "st-longhaul",
    name: "Long-Haul Recovery",
    category: "standing",
    minutes: [15, 20],
    tagline: "The longer version, for after a transatlantic flight or a full day in a car.",
    equipment: ["Nothing", "A wall or pillar helps, optional"],
    focus: ["Circulation", "Hip flexors", "Thoracic spine", "Neck"],
    notes: [
      "Eight hours in a seat leaves the hip flexors short, the thoracic spine flexed and the neck craned forward. This works those three in that order.",
      "Hold every stretch long. Under 45 seconds you are moving tissue around rather than changing it.",
      "Do this before you sleep off the jet lag, not after. It is far more effective on a body that is still warm from moving through an airport.",
    ],
    blocks: [
      {
        id: "stl-a",
        tag: "1",
        title: "Circulation",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 4,
        slots: [
          { ex: "standing-march", pres: "60s" },
          { ex: "calf-pump", pres: "25 reps" },
          { ex: "heel-toe-rocks", pres: "15 reps" },
        ],
      },
      {
        id: "stl-b",
        tag: "2",
        title: "Undo the seated position",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        note: "The hip flexor stretch is the one that matters most here. Give it the full minute.",
        slots: [
          { ex: "standing-hip-flexor", pres: "60s per side" },
          { ex: "standing-figure-four", pres: "60s per side" },
          { ex: "standing-forward-fold", pres: "60s" },
          { ex: "standing-calf-stretch", pres: "30s per side" },
        ],
      },
      {
        id: "stl-c",
        tag: "3",
        title: "Upper body and neck",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "chin-tuck", pres: "10 reps" },
          { ex: "standing-scap-squeeze", pres: "12 reps" },
          { ex: "doorway-chest", pres: "45s each side", note: "A door frame, a pillar corner, or a wall edge." },
          { ex: "standing-twist", pres: "8 per side" },
          { ex: "overhead-side-reach", pres: "30s per side" },
        ],
      },
      {
        id: "stl-d",
        tag: "4",
        title: "Down-regulate",
        kind: "straight",
        rounds: 1,
        minutes: 2,
        slots: [{ ex: "standing-breathing", pres: "2 min" }],
      },
    ],
  },

  {
    id: "st-prehab",
    name: "Standing Climber Prehab",
    category: "standing",
    minutes: [10, 14],
    tagline: "Fingers, elbows and shoulders on a travel day. No equipment, no floor, no excuses.",
    equipment: ["Nothing", "A hair tie or rubber band, optional"],
    focus: ["Finger extensors", "Rotator cuff", "Balance"],
    notes: [
      "A travel week is when antagonist work lapses, and lapsed antagonist work is what turns into golfer's elbow six weeks later.",
      "Every exercise here is isometric or self-resisted, so it needs nothing you are not already carrying.",
      "If you have a hair tie or a rubber band, use it for the finger extensions; it beats the self-resisted version.",
    ],
    blocks: [
      {
        id: "stp-a",
        tag: "1",
        title: "Fingers and forearms",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 4,
        slots: [
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "self-resisted-finger-ext", pres: "20 per hand" },
          { ex: "standing-wrist-stretch", pres: "30s each position" },
        ],
      },
      {
        id: "stp-b",
        tag: "2",
        title: "Shoulders",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 5,
        slots: [
          { ex: "standing-scap-squeeze", pres: "12 reps" },
          { ex: "self-resisted-er", pres: "6 x 10s per side" },
          { ex: "shoulder-rolls", pres: "10 each way" },
          { ex: "wall-pushup", pres: "15 reps", note: "Skip if there is no wall; the rest of the block still works." },
        ],
      },
      {
        id: "stp-c",
        tag: "3",
        title: "Feet and balance",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        slots: [
          { ex: "single-leg-balance", pres: "45s per side" },
          { ex: "heel-toe-rocks", pres: "15 reps" },
          { ex: "calf-pump", pres: "20 reps" },
        ],
      },
    ],
  },

  /* ======================== WARM-UP & RECOVERY ======================== */
  {
    id: "wu-express",
    name: "Express Climbing Warm-Up",
    category: "prep",
    minutes: [12, 15],
    tagline: "Minimum viable warm-up before you pull on anything hard.",
    equipment: ["Climbing wall", "Rubber band (optional)"],
    focus: ["Finger prep", "Movement", "Recruitment"],
    notes: [
      "Twelve minutes. Shorter than this and you are gambling with your fingers and shoulders.",
      "Order is deliberate: general, then local, then specific. Never load fingers before the pulse raiser.",
    ],
    blocks: [
      {
        id: "wux-a",
        tag: "1",
        title: "General",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        slots: [
          { ex: "pulse-raiser", pres: "3-4 min", note: "Enough to break a light sweat." },
          { ex: "finger-rolls", pres: "25 reps" },
        ],
      },
      {
        id: "wux-b",
        tag: "2",
        title: "Mobility",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "hip-circles", pres: "10 each direction" },
          { ex: "deep-squat-hold", pres: "30s" },
        ],
      },
      {
        id: "wux-c",
        tag: "3",
        title: "Finger & Shoulder Prep",
        kind: "circuit",
        rounds: 1,
        minutes: 3,
        slots: [
          { ex: "band-finger-ext", pres: "20 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "progressive-hangs", pres: "2 x 15s" },
        ],
      },
      {
        id: "wux-d",
        tag: "4",
        title: "On the Wall",
        kind: "circuit",
        rounds: 1,
        minutes: 5,
        slots: [
          { ex: "easy-climbing", pres: "3 problems" },
          { ex: "moderate-climbing", pres: "1-2 problems" },
        ],
      },
    ],
  },

  {
    id: "wu-full",
    name: "Full Climbing Warm-Up",
    category: "prep",
    minutes: [25, 30],
    tagline: "For hard sessions, cold gyms, or if you have a history of finger or elbow trouble.",
    equipment: ["Climbing wall", "Hangboard", "Rubber band"],
    focus: ["Thorough finger prep", "Mobility", "Recruitment pyramid"],
    notes: [
      "Use this before any session with max hangs, limit bouldering or a project attempt.",
      "The recruitment step at the end matters: it wakes the nervous system up so your first real attempt is not the warm-up for your second.",
    ],
    blocks: [
      {
        id: "wuf-a",
        tag: "1",
        title: "General",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "pulse-raiser", pres: "5 min" },
          { ex: "finger-rolls", pres: "30 reps" },
        ],
      },
      {
        id: "wuf-b",
        tag: "2",
        title: "Full Mobility",
        kind: "circuit",
        rounds: 1,
        minutes: 7,
        slots: [
          { ex: "arm-circles", pres: "10 each way" },
          { ex: "shoulder-pass-through", pres: "12 reps" },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "thoracic-rotation", pres: "6 per side" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
          { ex: "high-step-drill", pres: "8 per side" },
          { ex: "deep-squat-hold", pres: "40s" },
        ],
      },
      {
        id: "wuf-c",
        tag: "3",
        title: "Shoulder & Finger Activation",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 6,
        slots: [
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "scap-pull", pres: "8 reps" },
          { ex: "prone-ytw", pres: "5 each position" },
          { ex: "band-finger-ext", pres: "20 reps" },
        ],
      },
      {
        id: "wuf-d",
        tag: "4",
        title: "Progressive Hangs",
        kind: "circuit",
        rounds: 1,
        minutes: 4,
        note: "Feet-assisted to full bodyweight, big holds only.",
        slots: [{ ex: "progressive-hangs", pres: "3-4 x 10-15s" }],
      },
      {
        id: "wuf-e",
        tag: "5",
        title: "Climbing Pyramid",
        kind: "circuit",
        rounds: 1,
        minutes: 9,
        note: "Ramp the grade one step at a time. No jumping straight to your project.",
        slots: [
          { ex: "easy-climbing", pres: "4 problems" },
          { ex: "moderate-climbing", pres: "2-3 problems" },
          { ex: "campus-recruit", pres: "2-3 pulls" },
        ],
      },
    ],
  },

  {
    id: "wu-offwall",
    name: "Pre-Gym Activation (No Wall)",
    category: "prep",
    minutes: [10, 12],
    tagline: "Do this at home or in the parking lot so you arrive already warm.",
    equipment: ["Floor", "Rubber band"],
    focus: ["Desk-body reset", "Hip and shoulder range", "Finger prep"],
    notes: [
      "Built for arriving at the gym after a day at a desk. It does not replace on-the-wall warm-up, it shortens it.",
      "Pair it with the express warm-up at the gym for a complete ramp in about 20 minutes total.",
    ],
    blocks: [
      {
        id: "wuo-a",
        tag: "1",
        title: "Raise & Reset",
        kind: "circuit",
        rounds: 2,
        rest: "none",
        minutes: 6,
        slots: [
          { ex: "pulse-raiser", pres: "2 min", note: "Stairs, jumping jacks or a brisk walk." },
          { ex: "cat-cow", pres: "8 reps" },
          { ex: "thoracic-rotation", pres: "6 per side" },
          { ex: "worlds-greatest-stretch", pres: "5 per side" },
        ],
      },
      {
        id: "wuo-b",
        tag: "2",
        title: "Activate",
        kind: "circuit",
        rounds: 2,
        rest: "30s",
        minutes: 6,
        slots: [
          { ex: "scap-pushup", pres: "10 reps" },
          { ex: "prone-ytw", pres: "5 each position" },
          { ex: "glute-bridge", pres: "10 per side" },
          { ex: "finger-rolls", pres: "30 reps" },
          { ex: "band-finger-ext", pres: "20 reps" },
        ],
      },
    ],
  },

  {
    id: "cool-recovery",
    name: "Post-Session Recovery",
    category: "prep",
    minutes: [15, 20],
    tagline: "Flush the forearms, open what climbing shortened, down-regulate.",
    equipment: ["Floor", "Doorway"],
    focus: ["Forearm recovery", "Hip and chest mobility", "Down-regulation"],
    notes: [
      "Most useful immediately after climbing, while tissue is still warm. Second best is the same evening.",
      "The finger extensor and wrist work here is the same insurance as on strength days. Climbing is all flexion; something has to balance it.",
    ],
    blocks: [
      {
        id: "cr-a",
        tag: "1",
        title: "Flush",
        kind: "circuit",
        rounds: 1,
        minutes: 6,
        slots: [
          { ex: "cool-down-climb", pres: "3-5 min", note: "Skip if you are already off the wall." },
          { ex: "band-finger-ext", pres: "25 reps" },
          { ex: "forearm-flush", pres: "90s" },
        ],
      },
      {
        id: "cr-b",
        tag: "2",
        title: "Open",
        kind: "circuit",
        rounds: 1,
        minutes: 8,
        slots: [
          { ex: "doorway-chest", pres: "45s each position" },
          { ex: "pigeon-stretch", pres: "60-90s per side" },
          { ex: "hamstring-stretch", pres: "60s per side" },
          { ex: "thoracic-rotation", pres: "6 per side" },
        ],
      },
      {
        id: "cr-c",
        tag: "3",
        title: "Down-Regulate",
        kind: "straight",
        rounds: 1,
        minutes: 3,
        slots: [{ ex: "nasal-breathing", pres: "2-3 min" }],
      },
    ],
  },
];

export function planById(id: string): Plan | undefined {
  return PLANS.find((p) => p.id === id);
}

export function totalSlots(plan: Plan): number {
  return plan.blocks.reduce((n, b) => n + b.slots.length * b.rounds, 0);
}
